name: ci

on:
  push:
  pull_request:

jobs:
  import-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install light deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Static import sanity
        run: |
          python - << 'PY'
          import importlib
          # Các module không nên import heavy deps khi chỉ import cấp package
          import src.utils.config as cfg
          import src.pipeline as pipe
          import src.models.similarity as sim
          import src.models.clustering as cl
          print("Imports OK")
          PY

      # Không có data thì không build; chỉ kiểm tra tồn tại file & schema hợp lệ
      - name: Lint basic (optional)
        run: |
          python -m compileall -q src
