name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke build (no data check)
        run: |
          # nếu không có data/Coursera.csv trong repo public,
          # bước này chỉ kiểm tra import & lệnh help
          python - << 'PY'
import runpy
print("Imports OK")
PY
